name: Build pve-qemu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/chocrates/qemu-build:main
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Qemu
        run: |
          git clone git://git.proxmox.com/git/pve-qemu.git
      - name: Build Qemu
        if: false
        run: |
          pwd
          ls -al
          # Switch to the QEMU root directory.
          cd qemu
          # Prepare a native debug build.
          mkdir -p bin/debug/native
          cd bin/debug/native
          # Configure QEMU and start the build.
          ../../../configure --enable-debug
          make
          # Return to the QEMU root directory.
          cd ../../..
      - name: Build pve-qemu
        run: |
          cd pve-qemu
          mk-build-deps --install
          COMMAND=$(echo "\t\tmv ../qemu-bypass.8.1.2.patch . && patch -p1 < qemu-bypass.8.1.2.patch")
          sed  -i "/# guest-agent is only required for guest systems/i$COMMAND" debian/rules
          cat debian/rules
          make clean distclean
          make
          ls -l
