on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:12
    steps:     
      - name: Install Tools
        run: |
          apt-get update
          apt-get install -y wget
          echo "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription" | tee -a /etc/apt/sources.list 
          wget -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg "https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg"
          apt-get update
          apt-get install -y libzstd1 libproxmox-backup-qemu0-dev
          apt-get install -y git make libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build \
            build-essential libaio-dev libbluetooth-dev libcapstone-dev libbrlapi-dev libbz2-dev \
            libcap-ng-dev libcurl4-gnutls-dev libgtk-3-dev libibverbs-dev libjpeg8-dev libncurses5-dev \
            libnuma-dev librbd-dev librdmacm-dev libsasl2-dev libsdl2-dev libseccomp-dev libsnappy-dev \
            libssh-dev libvde-dev libvdeplug-dev libvte-2.91-dev libxen-dev liblzo2-dev valgrind xfslibs-dev \
            libnfs-dev libiscsi-dev equivs devscripts
          apt-get install -y autotools-dev autogen dh-autoreconf dkms doxygen check pkg-config \
            groff quilt dpatch automake autoconf libtool lintian libdevel-cycle-perl \
            libjson-perl libcommon-sense-perl liblinux-inotify2-perl libio-stringy-perl \
            libstring-shellquote-perl dh-systemd rpm2cpio libsqlite3-dev sqlite3 \
            libglib2.0-dev librrd-dev librrds-perl rrdcached libdigest-hmac-perl \
            libxml-parser-perl gdb libcrypt-openssl-random-perl \
            libcrypt-openssl-rsa-perl libnet-ldap-perl libauthen-pam-perl \
            libjson-xs-perl libterm-readline-gnu-perl oathtool libmime-base32-perl \
            liboath0 libpci-dev texi2html libsdl1.2-dev libgnutls28-dev \
            libspice-protocol-dev xfslibs-dev libnuma-dev libaio-dev \
            pve-libspice-server-dev libusbredirparser-dev glusterfs-common \
            libusb-1.0-0-dev librbd-dev libpopt-dev iproute bridge-utils numactl \
            glusterfs-common ceph-common python-ceph libgoogle-perftools4 \
            libfile-chdir-perl lvm2 glusterfs-client liblockfile-simple-perl \
            libsystemd-dev libreadline-gplv2-dev libio-multiplex-perl \
            libnetfilter-log-dev libipset3 ipset socat libsasl2-dev libogg-dev \
            python-pyparsing libfilesys-df-perl libcrypt-ssleay-perl \
            libfile-readbackwards-perl libanyevent-perl libanyevent-http-perl \
            unzip liblocale-po-perl libfile-sync-perl cstream \
            lzop dtach hdparm gdisk parted ttf-dejavu-core \
            liblzma-dev dosfstools mtools libxen-dev libfuse-dev libcpg-dev libquorum-dev \
            libcmap-dev libuuid-perl libqb-dev libapparmor-dev docbook2x libcap-dev \
            dh-apparmor graphviz libseccomp-dev libglib-perl libgtk3-perl libnss3-dev \
            libdlm-dev libudev-dev asciidoc-dblatex source-highlight libiscsi-dev \
            libiscsi7 librsvg2-bin libarchive-dev libgpgme-dev libcurl4-gnutls-dev \
            libtest-mockmodule-perl libjemalloc-dev libjpeg-dev
      - name: Checkout Qemu
        run: |
          git clone git://git.proxmox.com/git/pve-qemu.git
      - name: Build Qemu
        if: false
        run: |
          pwd
          ls -al
          # Switch to the QEMU root directory.
          cd qemu
          # Prepare a native debug build.
          mkdir -p bin/debug/native
          cd bin/debug/native
          # Configure QEMU and start the build.
          ../../../configure --enable-debug
          make
          # Return to the QEMU root directory.
          cd ../../..
      - name: Build pve-qemu
        run: |
          cd pve-qemu
          mk-build-deps --install
          make clean distclean
          make
          ls -l
